### PR TITLE
Add a small addition

### PR DESCRIPTION
**Pull request by verpixelt**

### CODE REVIEW

**Comment by zoepage** [comment]
We decided to not use homebrew in the installation, because there pop up problems with it... :/

**Comment by janl** [comment]
but we’d gladly take the whitespace fixes :D

**Comment by verpixelt** [comment]
@zoepage what exactly do you mean with pop up problems?

**Comment by zoepage** [comment]
There were issues with compromised packages / packages with errors. So we decided to use the original sources.

**Comment by janl** [comment]
Also: homebrew and node/npm were never working well together for historic reasons, this causes more problems for newcomers than is worth the convenience for experts, who know how to use homebrew anyway :)

**Comment by verpixelt** [comment]
Okay, thanks for the info =)

**Pull request closed without merging**
