### PR TITLE
fixed the numbering layout

### PR DESCRIPTION
**Pull request by pmbanugo**
fixed mistake with the numbers listed. It was numbered incorrectly and included a step from the old doc.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Hi @pmbanugo thank you for noticing this and making a Pull Request to fix this! It looks good to me. 👍 lgtm!

**Comment by machikoyasuda** [comment]
One last thing! Could you re-word your commit message to be in this format:

`docs: fixed the numbering layout`? 

We try to stick to these commit message styles: https://github.com/hoodiehq/hoodie/blob/master/CONTRIBUTING.md#pull-requests

**Review by machikoyasuda — APPROVED** [review]

**Comment by pmbanugo** [comment]
oh just noticed. Sorry :) I don't even know how to do that yet :D

**Comment by machikoyasuda** [comment]
@pmbanugo No worries! @gr2m taught me how to use the `Squash & Merge` button on github.com, so I did it myself :)

**Comment by gr2m** [comment]
Thanks @pmbanugo! I’ve also invited you to the Hoodie Contributors, welcome :) As Contributor, you don’t need to create forks any more, you can create branches on our repositories and send pull requests from there, which makes it a bit simpler for us to collaborate on them and to set them up locally :)

**Comment by pmbanugo** [comment]
Yeah Got the invite. Thanks :)

**Pull request merged**
