### PR TITLE
Jan review

### PR DESCRIPTION
**Pull request by janl**
cc #34

### CODE REVIEW

**Comment by janl** [comment]
This is fantastic work, thank you so much @snnd!

**Comment by boennemann** [comment]
My review on top of that: https://github.com/hoodiehq/documentation/pull/71

**Comment by zoepage** [comment]
fork by boenemann and after fixing typos, new PR.

**Comment by boennemann** [comment]
@zoepage My pr #71 was on top of jan's pr here, so we'd still have to merge this :)

**Comment by zoepage** [comment]
could you please take care of it @boennemann ? thank you <3

**Comment by boennemann** [comment]
@zoepage done <3

**Pull request merged**
