### PR TITLE
Issue 25 - camp tutorial update

### PR DESCRIPTION
**Pull request by pinglinh**
Hi, I've added the tutorial from `en` to `camp` folder 😄

### CODE REVIEW

**Comment by gr2m** [comment]
hey @pinglinh, I had a quick look and unfortunately there is more work than copying the tutorial from `en` to `camp`, but it’s the perfect start, and we can go trough together to adapt it to Hoodie’s new API. 

I didn’t find the time yet but will hope to have a look this week. :bear: Bear with us :)

**Comment by pinglinh** [comment]
@gr2m Ah okay no worries! When you're ready we can discuss what changes you want to be made and hopefully I can help 😄

**Comment by gr2m** [comment]
@pinglinh I’ll have time over the next two weeks. Are you around?

**Comment by gr2m** [comment]
Hey Linh, how are things looking for ya?

**Comment by pinglinh** [comment]
@gr2m Hey Gregor! So sorry for the late reply! Let me know what changes you'd like and I'll see if I can do some of them 😃

**Comment by gr2m** [comment]
This week’s very busy, but next week looks better for me, I’ll get back to you with more instructions and walk you trough the next steps :)

**Comment by pinglinh** [comment]
@gr2m Awesome! Looking forward to hearing from you 😄

**Comment by gr2m** [comment]
see my comment at https://github.com/hoodiehq/camp/issues/25#issuecomment-275897620 :)

**Pull request closed without merging**
