### PR TITLE
Jekyll update

### PR DESCRIPTION
**Pull request by gr2m**
follow up for https://github.com/hoodiehq/hood.ie/pull/257

### CODE REVIEW

**Comment by gr2m** [comment]
Hey @yuloh I’ve updated our http://docs.hood.ie `gh-pages` repository based on your pull-request hoodiehq/hood.ie#257. It all looks good, but I get a deprecation warning, that í don’t know how to get rid of (there is no `auto:true` in the _config.yml).

```
bundle exec jekyll serve
Configuration file: /Users/gregor/Projects/hoodie/documentation/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
            Source: /Users/gregor/Projects/hoodie/documentation
       Destination: /Users/gregor/Projects/hoodie/documentation/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.927 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Configuration file: /Users/gregor/Projects/hoodie/documentation/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

any idea?

**Comment by gr2m** [comment]
I merged it in to move on with this, but the deprecated message ^^ still occurs

**Comment by gr2m** [comment]
oh, I also got this error message via email:

---

The page build completed successfully, but returned the following warning: 

You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown. 

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies: 

https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0 

For information on troubleshooting Jekyll see: 

https://help.github.com/articles/troubleshooting-jekyll-builds 

If you have any questions you can contact us by replying to this email.

**Comment by matt-allan** [comment]
The deprecation notice for auto generation is apparently a bug in Jekyll.

https://github.com/jekyll/jekyll/issues/4830
https://github.com/jekyll/jekyll/issues/4831
https://github.com/github/pages-gem/issues/280

It was supposed to be fixed by [this commit](https://github.com/github/pages-gem/commit/065d40862e4e6e3150b1329ad72a95557e36a818), but that doesn't fix it for me locally.  The workaround isn't working either.  Still looking into it.  Edit: I guess that fix doesn't actually fix the root problem, as per [the last comment here](https://github.com/github/pages-gem/issues/280).

The github email was caused by switching `markdown: kramdown` to `markdown: redcarpet` in `_config,yml`.  Using the [settings from here](https://github.com/hoodiehq/hood.ie/blob/gh-pages/_config.yml#L8) should work.  I will do a PR after I finish looking into the Jekyll bug.

**Pull request merged**
