### PR TITLE
fix for custom fonts

### PR DESCRIPTION
**Pull request by zoepage**

### CODE REVIEW

**Comment by zoepage** [comment]
please review cc @gr2m @janl @espy

**Comment by gr2m** [comment]
Looks good from looking at the code

**Comment by janl** [comment]
Looks good running locally!

I just notice the thing where the typeface is lighter (as in low-contrast, barely readable) than we have on the main site, I remember @zoepage having a fix for that somewhere:

screen shot 2014-12-25 at 14 41 09

**Comment by zoepage** [comment]
Sadly, @verpixelt has a fix for that. Really no idea why this works differently although the CSS is the same. :/

**Pull request merged**
